version: '3.4'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=bank
      - MYSQL_USER=guest
      - MYSQL_ROOT_PASSWORD=guest
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  angularbank:
    container_name: angularbank
    build: .
    ports:
      - "4200:80"
